services:
  backendapp:
    image: ${DOCKER_REGISTRY-}backendapp
    container_name: backendapp
    build:
      context: .
      dockerfile: BackEndApp/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=databaseName
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/products-db:/var/lib/postgresql/data
    ports:
      - 5432:5432